### PR TITLE
ESP32 support for M5Stack Core2 IoT EduKit

### PR DESCRIPTION
**Pull request by torntrousers**
I'd like to use this library with the [M5Stack Core2 IoT EduKit](https://m5stack-store.myshopify.com/products/m5stack-core2-esp32-iot-development-kit-for-aws-iot-edukit) but there is a compile error on an ESP32 and the I2C address of the ATECC608 is different.

The compile error fix is from #25 

For the I2C address I can see that with the existing code you can create your own instance with a custom I2C address, but then all the provided utilities don't work so you'd need you own of those too, so this new ```begin(i2cAddr)``` function makes it all work more seemlessly.

What do you think?

### CODE REVIEW

**Comment by torntrousers** [comment]
I've tried this on the ESP32 and an Arduino Nano 33 IoT so can confirm it still works with both.

**Comment by rashedtalukder** [comment]
@facchinm, would you be so kind as to review this PR and merge? This patch lets me use this library on other Arduino boards with external ECCx08 boards that have a different i2c address.

**Comment by facchinm** [comment]
Hi @rashedtalukder , reviewing right now, sorry but I lost the notification :sweat: 

@torntrousers I really like the `begin()` overload; about the `requestFrom` change, I'd prefer to have the whole code without `ifdefs`, since the ESP32 version could not read more than 256 bytes and would wrap if more are requested while the other can (this shouldn't hurt the behaviour of the library but it's not very clear anyway). 

Maybe it's better to convince the ESP32 people to patch their core to be compliant with the API specifications https://github.com/arduino/ArduinoCore-API/blob/173e8eadced2ad32eeb93bcbd5c49f8d6a055ea6/api/HardwareI2C.h#L39 :wink:

**Comment by torntrousers** [comment]
Hi @facchinm , how about simply changing the ```(size_t)responseSize``` to ```(uint8_t)responseSize``` on the [requestFrom call](https://github.com/arduino-libraries/ArduinoECCX08/blob/master/src/ECCX08.cpp#L724)? Maybe that will seem imperfect, but it would fix https://github.com/arduino-libraries/ArduinoECCX08/issues/25 and https://github.com/arduino-libraries/ArduinoECCX08/issues/36 and keep the existing Arduino boards working fine.

**Comment by torntrousers** [comment]
Happy days, the requestFrom function has now been updated in the ESP32 core code in https://github.com/espressif/arduino-esp32/pull/5768 thanks to help from @me-no-dev. 
So I've updated this PR to juct have the I2C address update. How does this look now @facchinm ?

**Comment by rashedtalukder** [comment]
Awesome work @torntrousers! @facchinm, there shouldn't be any blockers to this getting merged at this point, correct?

**Comment by facchinm** [comment]
LGTM! I'm squashing into a single commit and merging! Thanks for the contribution

**Comment by torntrousers** [comment]
Any chance of a release of this library soon?

@rashedtalukder - I'm now trying to get a mutual TLS connection to AWS IoT with the client private key in the EduKit's 608. Using BearSSL as I've got that working with the 608 on a Nano 33 IoT board, but if you have this with MBedTLS or any ideas would be happy to hear about it.

**Comment by rashedtalukder** [comment]
@torntrousers, you can find an example of it working on the Core2 for AWS using BearSSL below. It would be great to have the device certificate get retrieved in BearSSL so there's less the user needs to do:
https://github.com/aws-samples/aws-iot-edukit-examples/tree/main/Basic_Arduino

You can see how to generate the public key in either of these examples:
- https://github.com/m5stack/Core2-for-AWS-IoT-EduKit/blob/master/Hardware-Features-Demo/main/atecc608_test.c#L166
- https://github.com/espressif/esp-cryptoauthlib/blob/feature/add_firmware_source_code/esp_cryptoauth_utility/firmware/main/handlers.c#L274

Here is how the device certificate is retrieved using the Microchip cryptoauthlib (along w/ espressif's port). You'll have to ignore the gibberish logging outputs in that function, it was clearly copied and pasted from the the signer cert retrieval.: https://github.com/espressif/esp-cryptoauthlib/blob/feature/add_firmware_source_code/esp_cryptoauth_utility/firmware/main/handlers.c#L513

**Comment by gannaramu** [comment]
@rashedtalukder I was able to extract the signer certificate and signer public key from the ATECC608B-TNGTLS but I am kind of stuck in reconstructing the certificate to X.509 format. with some guidance, I can get that going.

**Comment by torntrousers** [comment]
@rashedtalukder 
> It would be great to have the device certificate get retrieved in BearSSL so there's less the user needs to do

I guess that would need something like a new ArduinoECCX08 function that reconstructs a certificate to PEM format from a 608 slot and a new ArduinoBearSSL setEccSlot function that uses that:
```
void BearSSLClient::setEccSlot(int ecc508KeySlot, int ecc508CertificateSlot)
{
   String certPEM = ECCX08Cert.certificate(ecc508CertificateSlot);
   setEccSlot(ecc508KeySlot, certPEM.c_str());
}
```
Seems pretty dooable, and I do actually need the ECCX08Cert.certificate function for another thing anyway .

**Comment by torntrousers** [comment]
> 
> 
> @rashedtalukder I was able to extract the signer certificate and signer public key from the ATECC608B-TNGTLS but I am kind of stuck in reconstructing the certificate to X.509 format. with some guidance, I can get that going.

Hi @gannaramu , i could help you but I don't know what you know. The compressed certificates are described in section 2.2.1.3 [here](https://ww1.microchip.com/downloads/en/DeviceDoc/ATECC608B-TFLXTLS-CryptoAuthentication-Data-Sheet-DS40002249A.pdf) and the app note that refers too, [here](https://www.microchip.com/en-us/application-notes/an8974).

There is a really handy online utility for showing the ASN.1 structure [https://lapo.it/asn1js/](https://lapo.it/asn1js/) which can be super helpful while debugging.

**Comment by rashedtalukder** [comment]
@torntrousers, that's correct you'd need to start by adding the function here to get the public key from the requested slot. I can't remember if it's in PEM or DER format, but I think it's DER. After that, BearSSL needs to have it modified that if using a secure element or PK from a slot, it just uses the certificate from the hardware instead.

**Comment by gannaramu** [comment]
@torntrousers Thanks for those links. Both the documents didn't cover where the organizationName, commonName is inferred from. I was using the  Jupiter notebooks from this [repository](https://github.com/MicrochipTech/cryptoauth_trustplatform_designsuite) with [Cryptoauth Trust Platform Development Kit](https://www.microchip.com/en-us/development-tool/DM320118).
From [resource generation notebook](https://github.com/MicrochipTech/cryptoauth_trustplatform_designsuite/blob/master/TrustnGO/00_resource_generation/TNGTLS_manifest_file_generation.ipynb) i was able extract the device certificate and signer certificate and used it for cross verify my functions on Arduino (Teensy) are generating it correctly.  I observed the common name is a serial number appended with a " ATECC". do you know if there are application notes that talk about reconstructing the TNGTLS certificate

**Comment by torntrousers** [comment]
> 
> 
> ... do you know if there are application notes that talk about reconstructing the TNGTLS certificate

How about section 4.5.3 in here: https://datasheet.octopart.com/ATSAMA5D27-WLSOM1-Microchip-datasheet-149595509.pdf

If thats not enough I contacts in Microchip I can ask.

**Comment by rashedtalukder** [comment]
@gannaramu, the data sheet provided and looking at some of the function definitions in CryptoAuthLib, I can start to see how it comes together but it would take a while to trace through all the calls. I would start here though:
https://github.com/MicrochipTech/cryptoauthlib/blob/d5fcc6002ab070264696a0621f40c626861630eb/app/tng/tng_atcacert_client.c#L58-L99

**Comment by rashedtalukder** [comment]
Here is a feature request issue in BearSSL for the subsequent feature after this repository supports the device certificate and public key feature: https://github.com/arduino-libraries/ArduinoBearSSL/issues/55

**Pull request merged**
