### PR TITLE
Fix ASN.1 signature length + append when value is zero

### LINKED ISSUE #13: Possible crash on signatureLength() and appendSignature()
Hi. There's a bug in ASN1Utils.cpp, in functions that deal with the creation of the signatures (signatureLength, appendSignature) where a value consisting of only zeros can cause problems.

`while (*r == 0x00 && rLength) {`
should be changed to:
`while (rLength && *r == 0x00) {`

and

`if (*r & 0x80) {`
should be changed to:
`if (rLength && *r & 0x80) {`

Similar changes should be granted to `s` and `sLength`.

Of course the probability of an all zeros signature is remote in a real-case scenario, but not in tests.

### PR DESCRIPTION
**Pull request by sandeepmistry**
Resolves #13.

### CODE REVIEW

**Comment by guillep2k** [comment]
This doesn't look good:
`while (*r == 0x00 && rLength > 1)`
The order is important: *r is accessed before checking it's pointing to valid data (rLength>0)

**Comment by guillep2k** [comment]
@sandeepmistry: see my proposal for this fix.

**Comment by guillep2k** [comment]
See my comment in the issue page. #13

**Comment by sandeepmistry** [comment]
Closing in favour of #16.

**Pull request closed without merging**
